/**
 * Curated metadata for the imported game catalogue: genres and featured picks.
 *
 * The 300+ games in production were imported from the optimized-settings
 * files, which carry a name and nothing else — no genre, no developer. That
 * left `game_categories` empty, so the Games page genre filter and the whole
 * Categories page returned zero results for every option. This table is the
 * missing metadata; `assign-genres.ts` replays it into the database.
 *
 * Slugs on the left must match `games.slug`; slugs on the right must match
 * `BROWSE_CATEGORIES` in seed-data.ts. Both sides are validated by the script,
 * which reports anything it cannot match rather than silently skipping it.
 */
export const GAME_GENRES: Record<string, string[]> = {
  'a-plague-tale-innocence': ['adventure', 'stealth', 'horror'],
  'a-plague-tale-requiem': ['adventure', 'stealth', 'horror'],
  'age-of-empires-iii': ['strategy'],
  'age-of-empires-iv': ['strategy'],
  'age-of-mythology-retold': ['strategy'],
  'alan-wake': ['action', 'horror', 'adventure'],
  'alan-wake-2': ['horror', 'adventure'],
  'alien-isolation': ['horror', 'stealth', 'survival'],
  'american-truck-simulator': ['simulation'],
  'apex-legends': ['fps', 'shooter', 'battle-royale'],
  'arena-breakout-infinite': ['fps', 'shooter', 'survival'],
  'ark-scorched-earth': ['survival', 'open-world', 'adventure'],
  'assassin-creed-mirage': ['action', 'adventure', 'stealth', 'open-world'],
  'assassin-s-creed-brotherhood': ['action', 'adventure', 'stealth', 'open-world'],
  'assassin-s-creed-chronicles-china': ['action', 'stealth', 'platformer'],
  'assassin-s-creed-iii': ['action', 'adventure', 'stealth', 'open-world'],
  'assassin-s-creed-iv-black-flag-freedom-cry': ['action', 'adventure', 'stealth', 'open-world'],
  'assassin-s-creed-revelations': ['action', 'adventure', 'stealth', 'open-world'],
  'assassin-s-creed-shadows': ['action', 'adventure', 'stealth', 'open-world', 'rpg'],
  'assassin-s-creed-syndicate': ['action', 'adventure', 'stealth', 'open-world'],
  'assassin-s-creed-syndicate-2': ['action', 'adventure', 'stealth', 'open-world'],
  'assassin-s-creed-unity': ['action', 'adventure', 'stealth', 'open-world'],
  'assassins-creed-odyssey': ['action', 'rpg', 'open-world', 'adventure'],
  'assassins-creed-origins': ['action', 'rpg', 'open-world', 'adventure'],
  'assassins-creed-valhalla': ['action', 'rpg', 'open-world', 'adventure'],
  'assetto-corsa': ['racing', 'simulation'],
  'atomic-heart': ['fps', 'action', 'adventure'],
  'avatar-frontiers-of-pandora': ['fps', 'action', 'open-world', 'adventure'],
  'avowed': ['rpg', 'action', 'adventure'],
  'baldur-s-gate-3': ['rpg', 'strategy', 'adventure'],
  'baldurs-gate-3-no-sub': ['rpg', 'strategy', 'adventure'],
  'batman-arkham-city-goty': ['action', 'adventure', 'stealth', 'open-world'],
  'batman-arkham-origins': ['action', 'adventure', 'stealth', 'open-world'],
  'battlefield-1': ['fps', 'shooter'],
  'battlefield-2': ['fps', 'shooter'],
  'battlefield-2042': ['fps', 'shooter'],
  'battlefield-3': ['fps', 'shooter'],
  'battlefield-4': ['fps', 'shooter'],
  'battlefield-hardline': ['fps', 'shooter'],
  'battlefield-v': ['fps', 'shooter'],
  'beamng-drive': ['simulation', 'racing'],
  'beast-of-reincarnation': ['action', 'rpg', 'adventure'],
  'beyond-two-souls': ['adventure'],
  'biomutant': ['action', 'rpg', 'open-world'],
  'bioshock-2': ['fps', 'shooter', 'adventure', 'horror'],
  'black-myth-wukong': ['action', 'rpg', 'soulslike'],
  'blair-witch': ['horror', 'adventure'],
  'bloodborne': ['action', 'rpg', 'soulslike', 'horror'],
  'bodycam': ['fps', 'shooter'],
  'borderlands-4': ['fps', 'shooter', 'rpg', 'open-world', 'comedy'],
  'bright-memory': ['fps', 'action', 'shooter'],
  'call-of-duty-advanced-warfare': ['fps', 'shooter'],
  'call-of-duty-black-ops-3': ['fps', 'shooter'],
  'call-of-duty-black-ops-6': ['fps', 'shooter'],
  'call-of-duty-black-ops-cold-war': ['fps', 'shooter'],
  'call-of-duty-black-ops-ii': ['fps', 'shooter'],
  'call-of-duty-modern-warfare': ['fps', 'shooter'],
  'call-of-duty-modern-warfare-3': ['fps', 'shooter'],
  'call-of-duty-modern-warfare-ii': ['fps', 'shooter'],
  'call-of-duty-modern-warfare-iii': ['fps', 'shooter'],
  'call-of-duty-vanguard': ['fps', 'shooter'],
  'call-of-duty-warzone': ['fps', 'shooter', 'battle-royale'],
  'call-of-duty-wwii': ['fps', 'shooter'],
  'call-of-juarez-the-cartel': ['fps', 'shooter'],
  'castlevania-lords-of-shadow-ue': ['action', 'adventure', 'platformer'],
  'clair-obscur-expedition-33': ['rpg', 'adventure'],
  'colin-mcrae-dirt-2': ['racing'],
  'colin-mcrae-rally-and-dirt': ['racing'],
  'control': ['action', 'shooter', 'adventure'],
  'counter-strike-2': ['fps', 'shooter'],
  'crash-bandicoot-4-it-s-about-time': ['platformer', 'adventure', 'comedy'],
  'crimson-desert': ['action', 'rpg', 'open-world', 'adventure'],
  'crysis': ['fps', 'shooter', 'open-world'],
  'crysis-2': ['fps', 'shooter'],
  'cuphead': ['platformer', 'action'],
  'cyberpunk-2077': ['rpg', 'fps', 'open-world', 'action'],
  'dante-s-inferno': ['action', 'adventure'],
  'dark-souls': ['action', 'rpg', 'soulslike'],
  'dark-souls-2-scholar-of-the-first-sin': ['action', 'rpg', 'soulslike'],
  'dark-souls-iii': ['action', 'rpg', 'soulslike'],
  'days-gone': ['action', 'survival', 'open-world', 'horror'],
  'days-gone-remastered': ['action', 'survival', 'open-world', 'horror'],
  'dead-island-2': ['action', 'rpg', 'horror', 'survival'],
  'death-stranding': ['adventure', 'action', 'open-world'],
  'deathloop': ['fps', 'shooter', 'action', 'stealth'],
  'delta-force': ['fps', 'shooter'],
  'detroit-become-human': ['adventure'],
  'deus-ex-human-revolution': ['rpg', 'fps', 'stealth', 'action'],
  'devil-may-cry-5': ['action', 'adventure'],
  'dirt-3': ['racing'],
  'dirt-5': ['racing'],
  'dirt-rally-2-0': ['racing', 'simulation'],
  'dishonored': ['action', 'stealth', 'fps'],
  'doom-eternal': ['fps', 'shooter', 'action'],
  'doom-the-dark-ages': ['fps', 'shooter', 'action'],
  'doomthedarkages': ['fps', 'shooter', 'action'],
  'dragon-age-ii': ['rpg', 'action', 'adventure'],
  'dragon-age-inquisition': ['rpg', 'action', 'open-world'],
  'dragon-age-inquisition-2': ['rpg', 'action', 'open-world'],
  'dragons-dogma-2': ['rpg', 'action', 'open-world', 'adventure'],
  'dying-light': ['action', 'survival', 'horror', 'open-world'],
  'dying-light-2': ['action', 'survival', 'horror', 'open-world'],
  'dying-light-2-stay-human': ['action', 'survival', 'horror', 'open-world'],
  'dying-light-the-beast': ['action', 'survival', 'horror', 'open-world'],
  'ea-sports-fc-24': ['sports'],
  'ea-sports-fc-25': ['sports'],
  'elden-ring-nightreign': ['action', 'rpg', 'soulslike'],
  'elden-ring-shadow-of-the-erdtree': ['action', 'rpg', 'soulslike', 'open-world'],
  'evil-west': ['action', 'shooter'],
  'fallout-3': ['rpg', 'fps', 'open-world', 'shooter'],
  'fallout-76': ['rpg', 'open-world', 'survival', 'shooter'],
  'far-cry-3': ['fps', 'shooter', 'open-world', 'action'],
  'far-cry-4': ['fps', 'shooter', 'open-world', 'action'],
  'far-cry-6': ['fps', 'shooter', 'open-world', 'action'],
  'far-cry-new-dawn': ['fps', 'shooter', 'open-world', 'action'],
  'fifa-18': ['sports'],
  'fifa-19': ['sports'],
  'fifa-20': ['sports'],
  'fifa-22': ['sports'],
  'fifa-23': ['sports'],
  'final-fantasy-vii-remake-intergrade': ['rpg', 'action', 'adventure'],
  'final-fantasy-xvi': ['rpg', 'action', 'adventure'],
  'forspoken': ['action', 'rpg', 'open-world'],
  'forspoken-no-sub': ['action', 'rpg', 'open-world'],
  'fortnite': ['shooter', 'battle-royale', 'survival'],
  'forza-horizon-2': ['racing', 'open-world'],
  'forza-horizon-3': ['racing', 'open-world'],
  'forza-horizon-4': ['racing', 'open-world'],
  'forza-horizon-6': ['racing', 'open-world'],
  'forza-motorsport': ['racing', 'simulation'],
  'frostpunk': ['strategy', 'survival', 'simulation'],
  'frostpunk-2': ['strategy', 'survival', 'simulation'],
  'gears-5': ['shooter', 'action'],
  'gears-of-war': ['shooter', 'action'],
  'ghost-of-tsushima': ['action', 'adventure', 'open-world', 'stealth'],
  'ghostwire-tokyo': ['action', 'horror', 'adventure', 'open-world'],
  'god-of-war': ['action', 'adventure', 'rpg'],
  'god-of-war-ascension': ['action', 'adventure'],
  'god-of-war-ghost-of-sparta': ['action', 'adventure'],
  'god-of-war-ii': ['action', 'adventure'],
  'god-of-war-ragnarok': ['action', 'adventure', 'rpg'],
  'gotham-knights': ['action', 'rpg', 'open-world'],
  'grand-theft-auto-online': ['action', 'open-world', 'shooter'],
  'grand-theft-auto-v-enhanced': ['action', 'open-world', 'shooter'],
  'grand-theft-auto-vice-city': ['action', 'open-world', 'shooter'],
  'grid-2': ['racing'],
  'grid-autosport': ['racing', 'simulation'],
  'gta-san-andreas': ['action', 'open-world', 'shooter'],
  'half-life-alyx': ['fps', 'shooter', 'adventure'],
  'halo-campaign-evolved': ['fps', 'shooter'],
  'hell-is-us': ['action', 'adventure', 'rpg'],
  'hellblade-senua-s-sacrifice': ['action', 'adventure', 'horror'],
  'high-on-life-2': ['fps', 'shooter', 'comedy'],
  'hitman-3': ['stealth', 'action', 'shooter'],
  'hogwarts-legacy': ['rpg', 'action', 'open-world', 'adventure'],
  'hollow-knight': ['metroidvania', 'platformer', 'action'],
  'horizon-forbidden-west': ['action', 'rpg', 'open-world', 'adventure'],
  'horizon-forbidden-west-complete-edition': ['action', 'rpg', 'open-world', 'adventure'],
  'horizon-zero-dawn-remastered': ['action', 'rpg', 'open-world', 'adventure'],
  'indiana-jones-and-the-great-circle': ['adventure', 'action', 'stealth'],
  'injustice-gods-among-us': ['fighting', 'action'],
  'inside': ['platformer', 'puzzle', 'adventure'],
  'inzoi': ['simulation'],
  'jusant': ['puzzle', 'adventure', 'platformer'],
  'kingdom-come-deliverance': ['rpg', 'open-world', 'action', 'adventure'],
  'kingdom-come-deliverance-2': ['rpg', 'open-world', 'action', 'adventure'],
  'left-4-dead': ['fps', 'shooter', 'horror', 'survival'],
  'lego-batman-legacy-of-the-dark-knight': ['action', 'adventure', 'comedy', 'platformer'],
  'lies-of-p': ['action', 'rpg', 'soulslike'],
  'life-is-strange': ['adventure'],
  'life-is-strange-before-the-storm': ['adventure'],
  'little-nightmares-ii': ['horror', 'platformer', 'puzzle', 'adventure'],
  'little-nightmares-iii': ['horror', 'platformer', 'puzzle', 'adventure'],
  'lords-of-the-fallen': ['action', 'rpg', 'soulslike'],
  'lords-of-the-fallen-2023': ['action', 'rpg', 'soulslike'],
  'mad-max': ['action', 'open-world', 'racing'],
  'mafia-definitive-edition': ['action', 'open-world', 'shooter'],
  'mafia-ii': ['action', 'open-world', 'shooter'],
  'mafia-iii': ['action', 'open-world', 'shooter'],
  'manor-lords': ['strategy', 'simulation'],
  'marvels-guardians-of-the-galaxy': ['action', 'adventure', 'comedy'],
  'marvels-spiderman-2': ['action', 'adventure', 'open-world'],
  'marvels-spiderman-miles-morales': ['action', 'adventure', 'open-world'],
  'marvels-spiderman-remastered': ['action', 'adventure', 'open-world'],
  'mass-effect-legendary-edition': ['rpg', 'shooter', 'adventure'],
  'max-payne-2': ['action', 'shooter'],
  'max-payne-3': ['action', 'shooter'],
  'metal-gear-solid-2-sons-of-liberty': ['stealth', 'action', 'adventure'],
  'metal-gear-solid-3-snake-eater': ['stealth', 'action', 'adventure'],
  'metal-gear-solid-master-collection-version': ['stealth', 'action', 'adventure'],
  'metal-gear-solid-snake-eater-2025': ['stealth', 'action', 'adventure'],
  'metal-gear-solid-v-ground-zeroes': ['stealth', 'action', 'open-world'],
  'metal-gear-solid-v-the-phantom-pain': ['stealth', 'action', 'open-world'],
  'metro-exodus': ['fps', 'shooter', 'survival', 'horror'],
  'metro-exodus-enhanced-edition': ['fps', 'shooter', 'survival', 'horror'],
  'metro-last-light': ['fps', 'shooter', 'survival', 'horror'],
  'microsoft-flight-simulator': ['simulation'],
  'middle-earth-shadow-of-mordor': ['action', 'open-world', 'adventure'],
  'middle-earth-shadow-of-war': ['action', 'open-world', 'adventure', 'rpg'],
  'mindseye': ['action', 'adventure', 'shooter'],
  'minecraft': ['survival', 'adventure', 'simulation'],
  'mortal-kombat': ['fighting', 'action'],
  'mortal-kombat-1': ['fighting', 'action'],
  'mortal-kombat-11': ['fighting', 'action'],
  'mortal-kombat-xl': ['fighting', 'action'],
  'mx-vs-atv-legends': ['racing', 'sports'],
  'need-for-speed-heat': ['racing', 'open-world'],
  'need-for-speed-hot-pursuit': ['racing'],
  'need-for-speed-most-wanted': ['racing', 'open-world'],
  'need-for-speed-payback': ['racing', 'open-world'],
  'need-for-speed-rivals': ['racing', 'open-world'],
  'need-for-speed-shift': ['racing', 'simulation'],
  'need-for-speed-the-run': ['racing'],
  'ninja-gaiden-4': ['action', 'adventure'],
  'nioh-3': ['action', 'rpg', 'soulslike'],
  'no-man-s-sky': ['survival', 'adventure', 'open-world', 'simulation'],
  'ori-and-the-blind-forest': ['metroidvania', 'platformer', 'adventure'],
  'outlast': ['horror', 'stealth', 'survival'],
  'pacific-drive': ['survival', 'simulation', 'horror', 'adventure'],
  'payday-3': ['fps', 'shooter', 'action'],
  'plants-vs-zombies-garden-warfare-2': ['shooter', 'comedy'],
  'prey': ['fps', 'shooter', 'horror', 'rpg'],
  'prince-of-persia': ['platformer', 'action', 'adventure'],
  'project-cars-3': ['racing', 'simulation'],
  'prototype': ['action', 'open-world'],
  'prototype-2': ['action', 'open-world'],
  'pubg-battlegrounds': ['shooter', 'battle-royale', 'survival'],
  'quantum-break': ['action', 'shooter', 'adventure'],
  'rage-2': ['fps', 'shooter', 'open-world', 'action'],
  'ready-or-not': ['fps', 'shooter', 'simulation'],
  'recore': ['action', 'adventure', 'platformer'],
  'red-dead-redemption': ['action', 'open-world', 'adventure', 'shooter'],
  'red-dead-redemption-2': ['action', 'open-world', 'adventure', 'shooter'],
  'resident-evil-2': ['horror', 'survival', 'action'],
  'resident-evil-3': ['horror', 'survival', 'action'],
  'resident-evil-4-remake': ['horror', 'survival', 'action', 'shooter'],
  'resident-evil-7-biohazard': ['horror', 'survival', 'fps'],
  'resident-evil-requiem': ['horror', 'survival', 'action'],
  'resident-evil-village': ['horror', 'survival', 'fps'],
  'returnal': ['shooter', 'action', 'horror'],
  'ride-6': ['racing', 'simulation'],
  'rise-of-the-tomb-raider': ['action', 'adventure', 'platformer'],
  'rocket-league': ['sports', 'racing'],
  'rust': ['survival', 'open-world', 'shooter'],
  'saints-row': ['action', 'open-world', 'shooter', 'comedy'],
  'samson': ['action', 'adventure'],
  'sekiro': ['action', 'soulslike', 'stealth', 'adventure'],
  'senua-s-saga-hellblade-ii': ['action', 'adventure', 'horror'],
  'shadow-of-the-tomb-raider-definitive-edition': ['action', 'adventure', 'platformer'],
  'shadow-of-war': ['action', 'open-world', 'adventure', 'rpg'],
  'shift-2-unleashed': ['racing', 'simulation'],
  'silent-hill-2': ['horror', 'survival', 'adventure'],
  'silent-hill-f': ['horror', 'survival', 'adventure'],
  'sniper-elite-4': ['shooter', 'stealth', 'action'],
  'sniper-elite-iii': ['shooter', 'stealth', 'action'],
  'sniper-elite-nazi-zombie-army-2': ['shooter', 'action', 'horror'],
  'sniper-ghost-warrior-contracts': ['shooter', 'stealth', 'fps'],
  'somerville': ['adventure', 'puzzle'],
  'sony-uncharted-legacy-of-thieves-collection': ['action', 'adventure', 'platformer'],
  'spec-ops-the-line': ['shooter', 'action'],
  'spider-man-miles-morales': ['action', 'adventure', 'open-world'],
  'spider-man-remastered': ['action', 'adventure', 'open-world'],
  'stalker-2-heart-of-chornobyl': ['fps', 'shooter', 'survival', 'open-world', 'horror'],
  'star-wars-jedi-survivor': ['action', 'adventure', 'soulslike'],
  'star-wars-outlaws': ['action', 'adventure', 'open-world', 'stealth'],
  'starfield': ['rpg', 'open-world', 'shooter', 'adventure'],
  'stellar-blade': ['action', 'adventure', 'rpg'],
  'stray': ['adventure', 'puzzle', 'platformer'],
  'tekken-8': ['fighting', 'action'],
  'the-alters': ['survival', 'simulation', 'adventure'],
  'the-crew-2': ['racing', 'open-world'],
  'the-crew-motorfest': ['racing', 'open-world'],
  'the-dark-pictures-anthology-the-devil-in-me': ['horror', 'adventure'],
  'the-elder-scrolls-v-skyrim': ['rpg', 'open-world', 'action', 'adventure'],
  'the-last-of-us': ['action', 'adventure', 'survival', 'horror'],
  'the-last-of-us-part-ii': ['action', 'adventure', 'survival', 'horror'],
  'the-matrix-awakens': ['action', 'adventure'],
  'the-sims-3': ['simulation'],
  'the-sims-4': ['simulation'],
  'the-witcher': ['rpg', 'action', 'adventure'],
  'the-witcher-2-assassins-of-kings': ['rpg', 'action', 'adventure'],
  'the-witcher-3-wild-hunt': ['rpg', 'open-world', 'action', 'adventure'],
  'thief-definitive-edition': ['stealth', 'action', 'adventure'],
  'titanfall-2': ['fps', 'shooter', 'action'],
  'tom-clancy-s-ghost-recon': ['shooter', 'fps', 'stealth'],
  'tom-clancy-s-ghost-recon-breakpoint': ['shooter', 'open-world', 'stealth'],
  'tom-clancy-s-ghost-recon-future-soldier': ['shooter', 'stealth', 'action'],
  'tom-clancy-s-ghost-recon-wildlands': ['shooter', 'open-world', 'stealth'],
  'tom-clancy-s-rainbow-six-extraction': ['fps', 'shooter'],
  'tom-clancy-s-rainbow-six-siege': ['fps', 'shooter'],
  'tom-clancy-s-splinter-cell': ['stealth', 'action'],
  'tom-clancy-s-splinter-cell-blacklist': ['stealth', 'action', 'shooter'],
  'tom-clancy-s-splinter-cell-conviction': ['stealth', 'action', 'shooter'],
  'tom-clancy-s-the-division-2': ['shooter', 'rpg', 'open-world'],
  'tomb-raider-goty-edition': ['action', 'adventure', 'platformer'],
  'total-war-warhammer-iii': ['strategy'],
  'trek-to-yomi': ['action', 'adventure'],
  'uncharted': ['action', 'adventure', 'platformer'],
  'uncharted-legacy-of-thieves': ['action', 'adventure', 'platformer'],
  'unravel-two': ['platformer', 'puzzle', 'adventure'],
  'until-dawn': ['horror', 'adventure'],
  'wanted-weapons-of-fate': ['action', 'shooter'],
  'war-thunder': ['simulation', 'shooter'],
  'warhammer-40000-space-marine-2': ['action', 'shooter'],
  'watch-dogs': ['action', 'open-world', 'stealth', 'shooter'],
  'watch-dogs-2': ['action', 'open-world', 'stealth', 'shooter'],
  'watch-dogs-legion': ['action', 'open-world', 'stealth', 'shooter'],
  'wo-long-fallen-dynasty': ['action', 'rpg', 'soulslike'],
  'wolfenstein-ii': ['fps', 'shooter', 'action'],
  'wolfenstein-the-new-order': ['fps', 'shooter', 'action'],
  'wrc-8-fia-world-rally-championship': ['racing', 'simulation'],
  'wuchang-fallen-feathers': ['action', 'rpg', 'soulslike'],
  'wwe-2k23': ['sports', 'fighting'],
};

/**
 * Games shown on the Recommended page and anywhere the `featured` flag is read.
 *
 * The imported catalogue had `featured = false` on all 300+ rows, so the
 * Recommended nav item permanently rendered its empty state. These are the
 * marquee titles people actually come here to tune. Admins can change the
 * selection from the admin Games tab afterwards — only `--refeature` overwrites
 * their choice.
 */
export const FEATURED_GAMES: string[] = [
  'cyberpunk-2077',
  'red-dead-redemption-2',
  'elden-ring-shadow-of-the-erdtree',
  'black-myth-wukong',
  'the-witcher-3-wild-hunt',
  'grand-theft-auto-v-enhanced',
  'alan-wake-2',
  'baldur-s-gate-3',
  'hogwarts-legacy',
  'starfield',
  'god-of-war-ragnarok',
  'marvels-spiderman-2',
  'stalker-2-heart-of-chornobyl',
  'kingdom-come-deliverance-2',
  'clair-obscur-expedition-33',
  'silent-hill-2',
  'resident-evil-4-remake',
  'horizon-forbidden-west-complete-edition',
  'counter-strike-2',
  'assassin-s-creed-shadows',
  'doom-the-dark-ages',
  'call-of-duty-black-ops-6',
  'the-last-of-us-part-ii',
  'ghost-of-tsushima',
];
